from django.urls import path     
from . import views
urlpatterns = [
    path('home', views.signin),	      
    path('', views.index),	      
    path('register', views.register),	      
    path('registerUser', views.registerUser),	      
    path('login', views.login),	      
    path('signin', views.signin),	      
    path('logout', views.logout),
    path('forgotPassword', views.forgotPassword),
    path('forgotPasswordSendEmail', views.forgotPasswordSendEmail),
    path('setNewPassword', views.setNewPassword),
    path('dashboard', views.dashboard),
    path('userProfile', views.userProfile),
    path('userCreate', views.userCreate),
    path('portfolioNew', views.portfolioNew),
    path('portfolioCreate', views.portfolioCreate),
    path('portfolioEdit/<int:id>', views.portfolioEdit),
    # path('portfolioSave/<int:id>', views.portfolioSave),
    path('projectNew', views.projectNew),
    path('projectEdit/<int:id>', views.projectEdit),
    # path('projectSave/<int:id>', views.projectSave),
    # path('websitePreview/<int:id>', views.websitePreview),
    # path('websiteCreate/<int:id>', views.websiteCreate),
]