# Generated by Django 2.2 on 2020-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozyfolio_app', '0002_auto_20200125_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headshot',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profileHighlight',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
